"""
Triangle and affine maths shared by the mesh build and its queries.

The red-refinement child ordering and its integer group tables, the smallest
singular value that scales the refinement criterion, the determinant of the
lens Jacobian and the criterion's sign of it, the minimum angle closure
compares, and the containment test and barycentric coordinates the
source-plane query reads. Nothing here calls the lens or knows about a mesh.
"""

from typing import Tuple

from ....backend_obj import ArrayLike, backend

__all__ = (
    "CHILD_VERTEX_INDICES",
    "ROOT_SHAPES",
    "shape_matrix",
    "child_matrix_tables",
    "sigma_min_2x2",
    "triangle_weights",
    "contains",
    "sanitize_bary",
    "min_angle",
)


# Indices into the stacked six-point array [theta1, theta2, theta3, m1, m2, m3]
# giving the four children in the orientation-preserving order
#   C_1 = (t1, m3, m2)  C_2 = (t2, m1, m3)  C_3 = (t3, m2, m1)  C_4 = (m1, m2, m3)
# with m_i the midpoint opposite theta_i.
CHILD_VERTEX_INDICES = ((0, 5, 4), (1, 3, 5), (2, 4, 3), (3, 4, 5))

# The two triangles splitting the unit cell along the (0,0)-(1,1) diagonal, both
# positively oriented. Note ``func/base.py`` builds its pair with *opposite*
# handedness; this module fixes that so orientation is globally consistent.
ROOT_SHAPES = (
    ((0, 0), (1, 1), (0, 1)),
    ((0, 0), (1, 0), (1, 1)),
)

# `CHILD_VERTEX_INDICES` as a single backend int64 array, built once, so
# `red_split` can gather all four children with one fancy-indexing op rather
# than three separate per-axis index lists.
_CHILD_VERTEX_INDEX_TABLE = backend.as_array(CHILD_VERTEX_INDICES, dtype=backend.int64)


def shape_matrix(tri):
    """
    Edge matrix ``P = [v1 - v0 | v2 - v0]`` of a triangle.

    Parameters
    ----------
    tri: ndarray
        Triangle vertices, shape ``(..., 3, 2)``.

        *Unit: arcsec*

    Returns
    -------
    ndarray
        Shape ``(..., 2, 2)``, the two edge vectors as columns.

        *Unit: arcsec*
    """
    return backend.stack(
        (tri[..., 1, :] - tri[..., 0, :], tri[..., 2, :] - tri[..., 0, :]), dim=-1
    )


def _derive_child_matrices():
    """Recover ``M_k`` from the child ordering, where ``P_k = (1/2) P M_k``."""
    parent = backend.as_array(
        [[0.0, 0.0], [3.0, 2.0], [-1.0, 5.0]], dtype=backend.float64
    )
    t1, t2, t3 = parent
    six = backend.stack([t1, t2, t3, (t2 + t3) / 2, (t3 + t1) / 2, (t1 + t2) / 2])
    P = shape_matrix(parent)
    rows = []
    for idx in CHILD_VERTEX_INDICES:
        Pk = shape_matrix(six[list(idx), :])
        exact = 2.0 * (backend.linalg.inv(P) @ Pk)
        rounded = backend.round(exact)
        if not bool(backend.allclose(exact, rounded, atol=1e-9)):
            raise AssertionError("child matrices are not integral")
        rows.append(backend.long(rounded))
    return backend.stack(rows)


def child_matrix_tables() -> (
    Tuple[ArrayLike, ArrayLike, ArrayLike, ArrayLike, ArrayLike]
):
    """
    Fixed tables for red refinement.

    Red refinement gives ``P_k = (1/2) P M_k`` with ``M_k`` a fixed integer matrix
    per child index, so by induction ``P`` at level ``d`` is ``2**-d * h0 * R @ G[c]``
    for one of finitely many group elements ``G[c]``. The group generated by the four
    ``M_k`` is ``{+-I, +-M_2, +-M_3}``, of order six, and both root shapes lie in a
    single orbit -- so the inverse table has exactly six entries, not one per level.

    Returns
    -------
    M: ndarray
        ``(4, 2, 2)`` int64 child matrices; every ``det M_k == +1``.
    G: ndarray
        ``(6, 2, 2)`` int64 group elements in canonical order.
    COMPOSE: ndarray
        ``(6, 4)`` int64 with ``G[COMPOSE[c, k]] == G[c] @ M[k]``.
    PINV0: ndarray
        ``(6, 2, 2)`` float64 with ``PINV0[c] == inv(R @ G[c])``, ``R`` the class-0
        root shape. A triangle of class ``c`` at level ``d`` has
        ``inv(P_child_k) == (2**(d + 1) / h0) * PINV0[COMPOSE[c, k]]``.
    ROOT_CLASS: ndarray
        ``(2,)`` int64 class index of each entry of :data:`ROOT_SHAPES`.
    """
    M = _derive_child_matrices()
    eye = backend.eye(2, dtype=backend.int64)
    G = backend.stack([eye, M[1], M[2], -eye, -M[1], -M[2]])

    lookup = {tuple(backend.to_numpy(G[c]).reshape(-1).tolist()): c for c in range(6)}
    compose_rows = []
    for c in range(6):
        row = []
        for k in range(4):
            product = G[c] @ M[k]
            key = tuple(backend.to_numpy(product).reshape(-1).tolist())
            if key not in lookup:
                raise AssertionError("child matrix group is not closed")
            row.append(lookup[key])
        compose_rows.append(row)
    COMPOSE = backend.as_array(compose_rows, dtype=backend.int64)

    R = shape_matrix(backend.as_array(ROOT_SHAPES[0], dtype=backend.float64))
    PINV0 = backend.stack(
        [
            backend.linalg.inv(R @ backend.to(G[c], dtype=backend.float64))
            for c in range(6)
        ]
    )

    root_class_values = []
    for s, shape in enumerate(ROOT_SHAPES):
        target = shape_matrix(backend.as_array(shape, dtype=backend.float64))
        match = None
        for c in range(6):
            if bool(
                backend.allclose(R @ backend.to(G[c], dtype=backend.float64), target)
            ):
                match = c
                break
        if match is None:  # pragma: no cover - guarded by test_group_tables_close_...
            raise AssertionError(f"root shape {s} is not in the orbit of R")
        root_class_values.append(match)
    ROOT_CLASS = backend.as_array(root_class_values, dtype=backend.int64)
    return M, G, COMPOSE, PINV0, ROOT_CLASS


_, _, COMPOSE, PINV0, ROOT_CLASS = child_matrix_tables()


def area2(tri):
    """
    Twice the signed area of each triangle.

    Parameters
    ----------
    tri: ArrayLike
        ``(K, 3, 2)`` vertices.

        *Unit: arcsec*

    Returns
    -------
    ArrayLike
        ``(K,)``, positive for a counter-clockwise triangle.

        *Unit: arcsec^2*
    """
    P = shape_matrix(tri)
    return P[:, 0, 0] * P[:, 1, 1] - P[:, 0, 1] * P[:, 1, 0]


def build_device():
    """The backend's default device, where every build runs."""
    return backend.device(backend.zeros((0,)))


def to_device(value, device):
    """
    ``value`` on ``device``: an array, or a NamedTuple of arrays and NamedTuples, field by field.

    Anything else is returned as it is.
    """
    if isinstance(value, tuple) and hasattr(value, "_fields"):
        return type(value)(*(to_device(v, device) for v in value))
    if hasattr(value, "shape"):
        return backend.to(value, device=device)
    return value


def is_member(sorted_values, values):
    """True where each of ``values`` is in the ascending ``sorted_values``."""
    if sorted_values.shape[0] == 0:
        return backend.zeros(
            values.shape, dtype=backend.bool, device=backend.device(values)
        )
    pos = backend.clamp(
        backend.searchsorted(sorted_values, values), 0, sorted_values.shape[0] - 1
    )
    return sorted_values[pos] == values


def csr_offsets(counts):
    """CSR offsets ``(n + 1,)`` of blocks of ``counts`` ``(n,)`` rows each."""
    zero = backend.zeros((1,), dtype=backend.int64, device=backend.device(counts))
    return backend.concatenate(
        (zero, backend.cumsum(backend.long(counts), dim=0)), dim=0
    )


def sigma_min_2x2(A):
    """
    Smallest singular value of a batch of 2x2 matrices, in closed form.

    Pulling a source-plane displacement back to the lens plane gives
    ``||dtheta|| <= ||dbeta|| / sigma_min(A)``, so ``sigma_min`` is the correct
    anisotropic contraction scale. ``det A = sigma_min * sigma_max`` conflates the
    two directions and is wrong near folds, where ``sigma_min -> 0`` while
    ``sigma_max`` stays order one.

    With ``F = ||A||_F**2`` and ``D = |det A|``, ``(sigma_max +- sigma_min)**2 =
    F +- 2D``. ``F - 2D >= 0`` holds in exact arithmetic but **not** in floating
    point -- for a near-conformal ``A`` it goes negative by an ulp, and the
    unguarded ``sqrt`` then returns ``NaN`` for the near-circularly-symmetric core
    of essentially every lens model. Hence the clip.

    ``sigma_min`` is returned as ``D / sigma_max`` rather than
    ``(sqrt(F + 2D) - sqrt(F - 2D)) / 2`` because the former is stable in the
    near-degenerate limit, which is exactly the near-caustic regime that drives
    refinement.

    The ``sigma_max == 0`` branch is exact, not a tolerance: ``sigma_max == 0`` iff
    ``A == 0``, whose smallest singular value is exactly zero. Do not replace it
    with ``max(sigma_min, eps)`` -- both ``backend.maximum`` and ``backend.clamp``
    propagate ``NaN``, so a floor would fail open.

    Parameters
    ----------
    A: ndarray
        Shape ``(..., 2, 2)``, float64.

    Returns
    -------
    ndarray
        Shape ``(...)``. Exactly ``0.0`` where ``A == 0``; ``NaN`` where ``A`` is
        non-finite, so that step 7 fails closed.
    """
    F = backend.sum(A**2, dim=(-2, -1))
    D = backend.abs(A[..., 0, 0] * A[..., 1, 1] - A[..., 0, 1] * A[..., 1, 0])
    sigma_max = (
        backend.sqrt(F + 2 * D) + backend.sqrt(backend.clamp(F - 2 * D, 0.0, None))
    ) / 2
    zero = sigma_max == 0
    # Double `where` keeps the division away from 0/0 without masking a NaN input:
    # a NaN sigma_max fails the `== 0` test, so NaN reaches the output.
    return backend.where(zero, 0.0, D / backend.where(zero, 1.0, sigma_max))


def triangle_weights(tri, beta) -> ArrayLike:
    """
    The three cross products that give containment and barycentric coordinates.

    With ``q1, q2, q3`` the triangle's mapped vertices, ``w_i`` is the cross
    product of the two edges of the sub-triangle opposite vertex ``i``. Then
    ``w1 + w2 + w3 == d`` identically, where ``d`` is twice the signed area, so
    ``w / d`` sums to one by construction and no matrix inverse is needed.

    Because a mesh vertex is stored once and referenced by index, two leaves
    sharing an edge form these products from bit-identical operands in opposite
    order. IEEE multiplication is commutative, so their weights on that edge are
    **exactly** negated and a query point can never fall through the seam between
    them.

    Parameters
    ----------
    tri: ArrayLike
        Source-plane triangle vertices, shape ``(T, 3, 2)``.

        *Unit: arcsec*

    beta: ArrayLike
        Query points, one per candidate, shape ``(T, 2)``.

        *Unit: arcsec*

    Returns
    -------
    ArrayLike
        Shape ``(T, 3)``.
    """
    q1 = tri[:, 0, :] - beta
    q2 = tri[:, 1, :] - beta
    q3 = tri[:, 2, :] - beta
    return backend.stack(
        (
            q2[:, 0] * q3[:, 1] - q2[:, 1] * q3[:, 0],
            q3[:, 0] * q1[:, 1] - q3[:, 1] * q1[:, 0],
            q1[:, 0] * q2[:, 1] - q1[:, 1] * q2[:, 0],
        ),
        dim=-1,
    )


def contains(w) -> ArrayLike:
    """
    Containment test: all three weights share a sign, zeros counting as inside.

    Source-plane images flip handedness across critical curves by design, so a
    fixed positive convention would be wrong on half the mesh. Since
    ``w1 + w2 + w3 == d``, "all three share a sign" implies that sign is
    ``sign(d)`` whenever ``d != 0`` -- so this is equivalent to testing against the
    triangle's own ``d``, while also being well defined when ``d`` is *exactly*
    zero. That case is reachable: three source-plane vertices can be exactly
    collinear in floating point, and a ``kappa = 1`` sheet maps every leaf to a
    point. Testing against ``sign(d) == 0`` would make every such leaf a hit for
    every query.

    Zeros counting as inside means a point on a shared edge returns both leaves.
    That is intended, and is the main reason candidate count is not image
    multiplicity.

    Parameters
    ----------
    w: ArrayLike
        Weights from :func:`triangle_weights`, shape ``(T, 3)``.

    Returns
    -------
    ArrayLike
        Shape ``(T,)`` bool.
    """
    nonneg = (w[..., 0] >= 0) & (w[..., 1] >= 0) & (w[..., 2] >= 0)
    nonpos = (w[..., 0] <= 0) & (w[..., 1] <= 0) & (w[..., 2] <= 0)
    return nonneg | nonpos


def sanitize_bary(w, d) -> ArrayLike:
    """
    Normalize weights to barycentric coordinates, clamping then falling back.

    ``d`` goes to zero on leaves straddling a critical curve, so ``w / d`` there is
    a ratio of two quantities at the roundoff floor -- unbounded, possibly outside
    the triangle, or ``NaN``. Two regimes, handled in order.

    The clip handles ordinary roundoff: a hit passed containment, so
    ``bary in [0, 1]**3`` holds mathematically and small excursions are numerical
    only. The centroid branch handles genuine breakdown, where ``w`` and ``d`` are
    both noise and the clipped components carry no information; it is also the only
    defined answer when they clip to all-zero. ``isfinite`` is checked *after* the
    clip, because clipping propagates ``NaN``.

    The centroid is a bounded fallback, not a guess. A leaf with ``d`` near zero
    reached the size floor, so its longest edge is at most ``min_img_sep`` and the
    centroid is within ``(2/3) * l_max`` of every point in it.

    Parameters
    ----------
    w: ArrayLike
        Weights of the hits, shape ``(K, 3)``.
    d: ArrayLike
        Twice the signed source-plane area of each hit leaf, shape ``(K,)``.

    Returns
    -------
    ArrayLike
        Shape ``(K, 3)``, guaranteed to lie in the simplex.
    """
    bary = backend.clamp(w / backend.unsqueeze(d, -1), 0.0, 1.0)
    total = bary[..., 0] + bary[..., 1] + bary[..., 2]
    ok = (
        (total > 0)
        & backend.isfinite(bary[..., 0])
        & backend.isfinite(bary[..., 1])
        & backend.isfinite(bary[..., 2])
    )
    safe = backend.where(ok, total, backend.ones_like(total))
    normed = bary / backend.unsqueeze(safe, -1)
    third = backend.ones_like(bary) / 3
    return backend.where(backend.unsqueeze(ok, -1), normed, third)


def min_angle(tri) -> ArrayLike:
    """
    Smallest interior angle of each triangle, in radians.

    Parameters
    ----------
    tri: ArrayLike
        Shape ``(n, 3, 2)``.

    Returns
    -------
    ArrayLike
        Shape ``(n,)``. Degenerate triangles give ``0.0`` rather than ``NaN``.
    """
    a = backend.norm(tri[:, 2] - tri[:, 1], dim=-1)
    b = backend.norm(tri[:, 0] - tri[:, 2], dim=-1)
    c = backend.norm(tri[:, 1] - tri[:, 0], dim=-1)
    # A degenerate triangle makes one of these a 0/0 division. Neither backend
    # warns the way NumPy's default error mode does, so there is no
    # `np.errstate` context to drop into an equivalent.
    cosines = backend.stack(
        (
            (b * b + c * c - a * a) / (2 * b * c),
            (c * c + a * a - b * b) / (2 * c * a),
            (a * a + b * b - c * c) / (2 * a * b),
        ),
        dim=1,
    )
    angles = backend.arccos(backend.clamp(cosines, -1.0, 1.0))
    # Both backends' `nan_to_num` already default a bare NaN to 0.0 when `nan`
    # is left unset -- matching the oracle's explicit `nan=0.0` -- and the
    # wrapper here does not itself expose a `nan` keyword.
    return backend.nan_to_num(backend.min(angles, dim=1))
