"""
Pure kernels for the adaptive lens-plane mesh.

This module has two clearly separated halves.

**Host-side build kernels** operate on ``backend`` float64 arrays during the
host-side mesh build. Keeping them in one numerical world is what makes the
``NaN`` semantics of :func:`sigma_min_2x2` and :func:`converged_from_deviation`
verifiable.

**Query kernels** operate on ``backend`` arrays and are used by ``Mesh.query``.
"""

import math
from typing import NamedTuple, Tuple

from ...backend_obj import ArrayLike, backend

__all__ = (
    "CHILD_VERTEX_INDICES",
    "ROOT_SHAPES",
    "shape_matrix",
    "child_matrix_tables",
    "affine_from_triangles",
    "sigma_min_2x2",
    "midpoint_deviation",
    "converged_from_deviation",
    "child_shape_matrices",
    "parity_from_children",
    "evaluate_criterion",
    "triangle_weights",
    "contains",
    "sanitize_bary",
    "MAX_KEY",
    "Lattice",
    "make_lattice",
    "lattice_key",
    "lattice_ij_from_key",
    "lattice_xy",
    "lattice_on_boundary",
    "depth_floor",
    "validate_build_args",
    "VertexCache",
    "empty_cache",
    "cache_size",
    "cache_lookup",
    "cache_missing",
    "cache_insert",
    "empty_active",
    "active_add_slots",
    "active_contains_slots",
    "active_contains",
    "LEAF_CONVERGED",
    "LEAF_SIZE_FLOOR",
    "LEAF_FORCED",
    "LEAF_INVALID",
    "LEAF_NONFINITE",
    "LeafStore",
    "empty_store",
    "store_add",
    "store_remove",
    "store_compact",
    "initial_triangles",
    "midpoint_ij",
    "red_split",
    "edge_quarter_keys",
    "find_unbalanced",
)

# ---------------------------------------------------------------------------
# Host-side build kernels (backend, float64)
# ---------------------------------------------------------------------------

# Indices into the stacked six-point array [theta1, theta2, theta3, m1, m2, m3]
# giving the four children in the orientation-preserving order
#   C_1 = (t1, m3, m2)  C_2 = (t2, m1, m3)  C_3 = (t3, m2, m1)  C_4 = (m1, m2, m3)
# with m_i the midpoint opposite theta_i.
CHILD_VERTEX_INDICES = ((0, 5, 4), (1, 3, 5), (2, 4, 3), (3, 4, 5))

# The two triangles splitting the unit cell along the (0,0)-(1,1) diagonal, both
# positively oriented. Note ``func/base.py`` builds its pair with *opposite*
# handedness; this module fixes that so orientation is globally consistent.
ROOT_SHAPES = (
    ((0, 0), (1, 1), (0, 1)),
    ((0, 0), (1, 0), (1, 1)),
)

# `CHILD_VERTEX_INDICES` as a single backend int64 array, built once, so
# `red_split` can gather all four children with one fancy-indexing op rather
# than three separate per-axis index lists.
_CHILD_VERTEX_INDEX_TABLE = backend.as_array(CHILD_VERTEX_INDICES, dtype=backend.int64)


def shape_matrix(tri):
    """
    Edge matrix ``P = [v1 - v0 | v2 - v0]`` of a triangle.

    Parameters
    ----------
    tri: ndarray
        Triangle vertices, shape ``(..., 3, 2)``.

        *Unit: arcsec*

    Returns
    -------
    ndarray
        Shape ``(..., 2, 2)``, the two edge vectors as columns.

        *Unit: arcsec*
    """
    return backend.stack(
        (tri[..., 1, :] - tri[..., 0, :], tri[..., 2, :] - tri[..., 0, :]), dim=-1
    )


def affine_from_triangles(p, q):
    """
    Linear part of the affine map reproducing three vertex correspondences.

    Invariant under any relabelling applied simultaneously to both triangles,
    which is what makes the parity test immune to vertex ordering.

    Parameters
    ----------
    p: ndarray
        Lens-plane triangle, shape ``(..., 3, 2)``.

        *Unit: arcsec*

    q: ndarray
        Source-plane triangle, shape ``(..., 3, 2)``.

        *Unit: arcsec*

    Returns
    -------
    ndarray
        Shape ``(..., 2, 2)``.
    """
    return shape_matrix(q) @ backend.linalg.inv(shape_matrix(p))


def _derive_child_matrices():
    """Recover ``M_k`` from the child ordering, where ``P_k = (1/2) P M_k``."""
    parent = backend.as_array(
        [[0.0, 0.0], [3.0, 2.0], [-1.0, 5.0]], dtype=backend.float64
    )
    t1, t2, t3 = parent
    six = backend.stack([t1, t2, t3, (t2 + t3) / 2, (t3 + t1) / 2, (t1 + t2) / 2])
    P = shape_matrix(parent)
    rows = []
    for idx in CHILD_VERTEX_INDICES:
        Pk = shape_matrix(six[list(idx), :])
        exact = 2.0 * (backend.linalg.inv(P) @ Pk)
        rounded = backend.round(exact)
        if not bool(backend.allclose(exact, rounded, atol=1e-9)):
            raise AssertionError("child matrices are not integral")
        rows.append(backend.long(rounded))
    return backend.stack(rows)


def child_matrix_tables() -> (
    Tuple[ArrayLike, ArrayLike, ArrayLike, ArrayLike, ArrayLike]
):
    """
    Fixed tables for red refinement.

    Red refinement gives ``P_k = (1/2) P M_k`` with ``M_k`` a fixed integer matrix
    per child index, so by induction ``P`` at level ``d`` is ``2**-d * h0 * R @ G[c]``
    for one of finitely many group elements ``G[c]``. The group generated by the four
    ``M_k`` is ``{+-I, +-M_2, +-M_3}``, of order six, and both root shapes lie in a
    single orbit -- so the inverse table has exactly six entries, not one per level.

    Returns
    -------
    M: ndarray
        ``(4, 2, 2)`` int64 child matrices; every ``det M_k == +1``.
    G: ndarray
        ``(6, 2, 2)`` int64 group elements in canonical order.
    COMPOSE: ndarray
        ``(6, 4)`` int64 with ``G[COMPOSE[c, k]] == G[c] @ M[k]``.
    PINV0: ndarray
        ``(6, 2, 2)`` float64 with ``PINV0[c] == inv(R @ G[c])``, ``R`` the class-0
        root shape. A triangle of class ``c`` at level ``d`` has
        ``inv(P_child_k) == (2**(d + 1) / h0) * PINV0[COMPOSE[c, k]]``.
    ROOT_CLASS: ndarray
        ``(2,)`` int64 class index of each entry of :data:`ROOT_SHAPES`.
    """
    M = _derive_child_matrices()
    eye = backend.eye(2, dtype=backend.int64)
    G = backend.stack([eye, M[1], M[2], -eye, -M[1], -M[2]])

    lookup = {tuple(backend.to_numpy(G[c]).reshape(-1).tolist()): c for c in range(6)}
    compose_rows = []
    for c in range(6):
        row = []
        for k in range(4):
            product = G[c] @ M[k]
            key = tuple(backend.to_numpy(product).reshape(-1).tolist())
            if key not in lookup:
                raise AssertionError("child matrix group is not closed")
            row.append(lookup[key])
        compose_rows.append(row)
    COMPOSE = backend.as_array(compose_rows, dtype=backend.int64)

    R = shape_matrix(backend.as_array(ROOT_SHAPES[0], dtype=backend.float64))
    PINV0 = backend.stack(
        [
            backend.linalg.inv(R @ backend.to(G[c], dtype=backend.float64))
            for c in range(6)
        ]
    )

    root_class_values = []
    for s, shape in enumerate(ROOT_SHAPES):
        target = shape_matrix(backend.as_array(shape, dtype=backend.float64))
        match = None
        for c in range(6):
            if bool(
                backend.allclose(R @ backend.to(G[c], dtype=backend.float64), target)
            ):
                match = c
                break
        if match is None:  # pragma: no cover - guarded by test_group_tables_close_...
            raise AssertionError(f"root shape {s} is not in the orbit of R")
        root_class_values.append(match)
    ROOT_CLASS = backend.as_array(root_class_values, dtype=backend.int64)
    return M, G, COMPOSE, PINV0, ROOT_CLASS


def sigma_min_2x2(A):
    """
    Smallest singular value of a batch of 2x2 matrices, in closed form.

    Pulling a source-plane displacement back to the lens plane gives
    ``||dtheta|| <= ||dbeta|| / sigma_min(A)``, so ``sigma_min`` is the correct
    anisotropic contraction scale. ``det A = sigma_min * sigma_max`` conflates the
    two directions and is wrong near folds, where ``sigma_min -> 0`` while
    ``sigma_max`` stays order one.

    With ``F = ||A||_F**2`` and ``D = |det A|``, ``(sigma_max +- sigma_min)**2 =
    F +- 2D``. ``F - 2D >= 0`` holds in exact arithmetic but **not** in floating
    point -- for a near-conformal ``A`` it goes negative by an ulp, and the
    unguarded ``sqrt`` then returns ``NaN`` for the near-circularly-symmetric core
    of essentially every lens model. Hence the clip.

    ``sigma_min`` is returned as ``D / sigma_max`` rather than
    ``(sqrt(F + 2D) - sqrt(F - 2D)) / 2`` because the former is stable in the
    near-degenerate limit, which is exactly the near-caustic regime that drives
    refinement.

    The ``sigma_max == 0`` branch is exact, not a tolerance: ``sigma_max == 0`` iff
    ``A == 0``, whose smallest singular value is exactly zero. Do not replace it
    with ``max(sigma_min, eps)`` -- both ``backend.maximum`` and ``backend.clamp``
    propagate ``NaN``, so a floor would fail open.

    Parameters
    ----------
    A: ndarray
        Shape ``(..., 2, 2)``, float64.

    Returns
    -------
    ndarray
        Shape ``(...)``. Exactly ``0.0`` where ``A == 0``; ``NaN`` where ``A`` is
        non-finite, so that step 7 fails closed.
    """
    F = backend.sum(A**2, dim=(-2, -1))
    D = backend.abs(A[..., 0, 0] * A[..., 1, 1] - A[..., 0, 1] * A[..., 1, 0])
    sigma_max = (
        backend.sqrt(F + 2 * D) + backend.sqrt(backend.clamp(F - 2 * D, 0.0, None))
    ) / 2
    zero = sigma_max == 0
    # Double `where` keeps the division away from 0/0 without masking a NaN input:
    # a NaN sigma_max fails the `== 0` test, so NaN reaches the output.
    return backend.where(zero, 0.0, D / backend.where(zero, 1.0, sigma_max))


def midpoint_deviation(beta_v, beta_m):
    """
    Distance between each mapped edge midpoint and its affine prediction.

    With ``m_i`` opposite ``theta_i``, the predicted image of ``m_i`` under an
    affine map is the mean of the two ``beta`` values at the endpoints of the edge
    it bisects, ``(beta_j + beta_k) / 2`` for cyclic ``(i, j, k)``.

    Parameters
    ----------
    beta_v: ndarray
        Source-plane vertices, shape ``(n, 3, 2)``.

        *Unit: arcsec*

    beta_m: ndarray
        Source-plane edge midpoints ``m1, m2, m3``, shape ``(n, 3, 2)``.

        *Unit: arcsec*

    Returns
    -------
    ndarray
        Shape ``(n, 3)``, a source-plane length.

        *Unit: arcsec*
    """
    predicted = 0.5 * (beta_v[:, [1, 2, 0], :] + beta_v[:, [2, 0, 1], :])
    return backend.norm(predicted - beta_m, dim=-1)


def converged_from_deviation(r, s, min_img_sep):
    """
    Step 7 of the refinement criterion.

    Written as ``all(r < threshold)`` and never as ``not any(r >= threshold)``.
    The two are not equivalent when ``s`` is ``NaN``: under IEEE every comparison
    against ``NaN`` is False, so the ``>=`` form would mark a maximally degenerate
    triangle *converged*, silently inverting the intended behaviour. The ``<`` form
    puts ``NaN`` in the split branch. It also settles the exact-equality edge -- an
    affine-but-singular triangle (``r == 0``, ``s == 0``) gives ``0 < 0``, False,
    and splits, which is the conservative direction.

    Note the comparison is evaluated in the **source plane**: ``r`` is a
    source-plane length and ``s`` is dimensionless, so ``s * min_img_sep`` converts
    the lens-plane tolerance ``min_img_sep`` into a source-plane one. The
    equivalent lens-plane form ``r / s < min_img_sep`` must not be used, because
    dividing by ``s`` breaks on the legal and expected ``s == 0``.

    Parameters
    ----------
    r: ndarray
        Midpoint deviations, shape ``(n, 3)``.

        *Unit: arcsec*

    s: ndarray
        Smallest singular value over the four children, shape ``(n,)``.
    min_img_sep: float
        Lens-plane tolerance.

        *Unit: arcsec*

    Returns
    -------
    ndarray
        Shape ``(n,)`` bool.
    """
    return backend.all(r < (s * min_img_sep)[:, None], dim=1)


def child_shape_matrices(beta_v, beta_m):
    """
    Source-plane edge matrices ``Q_k`` of the four red-split children.

    Split out of :func:`evaluate_criterion` so the parity test can be applied on
    its own at ``max_level``, where there is no split left to decide and the
    deviation half of the criterion does not run.

    Parameters
    ----------
    beta_v: ndarray
        Source-plane vertices, shape ``(n, 3, 2)``.

        *Unit: arcsec*

    beta_m: ndarray
        Source-plane midpoints ``m1, m2, m3``, shape ``(n, 3, 2)``.

        *Unit: arcsec*

    Returns
    -------
    ndarray
        Shape ``(n, 4, 2, 2)``, child index in :data:`CHILD_VERTEX_INDICES`
        order.
    """
    stacked = backend.concatenate([beta_v, beta_m], dim=1)  # (n, 6, 2)
    idx0, idx1, idx2 = zip(*CHILD_VERTEX_INDICES)  # each length 4
    q1 = stacked[:, list(idx0), :]
    q2 = stacked[:, list(idx1), :]
    q3 = stacked[:, list(idx2), :]
    return backend.stack((q2 - q1, q3 - q1), dim=-1)  # (n, 4, 2, 2)


def parity_from_children(Q):
    """
    True where ``sign(det Q_k)`` is constant over the four children.

    The parity test needs no lens-plane ``P`` at all: ``sign(det A_k) =
    sign(det Q_k) * sign(det P_k)``, and all four children share the parent's
    ``sign(det P_k)`` because every ``det M_k == +1``, so constancy of
    ``sign(det A_k)`` over ``k`` is equivalent to constancy of
    ``sign(det Q_k)``. That is what makes this usable at ``max_level``, where
    no child is ever built and no ``P`` is ever formed.

    A ``NaN`` never equals itself, so a non-finite child lands in the failing
    branch. An exact zero gives sign 0, which differs from ``+-1`` and also
    fails -- unless *every* child is zero, which is a constant sign and passes.

    Parameters
    ----------
    Q: ndarray
        Child edge matrices from :func:`child_shape_matrices`, shape
        ``(n, 4, 2, 2)``.

    Returns
    -------
    ndarray
        Shape ``(n,)`` bool.
    """
    det_q = Q[..., 0, 0] * Q[..., 1, 1] - Q[..., 0, 1] * Q[..., 1, 0]
    sign_q = backend.sign(det_q)
    return backend.all(sign_q == sign_q[:, :1], dim=1)


def quadratic_vertex_parity_ok(beta_v, beta_m):
    """Check parity agreement at the quadratic interpolant's vertices.

    Parameters
    ----------
    beta_v : ndarray, shape (n, 3, 2)
        Mapped triangle vertices.
    beta_m : ndarray, shape (n, 3, 2)
        Mapped edge midpoints, each opposite its corresponding vertex.

    Returns
    -------
    ndarray, shape (n,)
        True when all three estimated vertex determinants are finite
        and have the same strictly nonzero sign.

    Notes
    -----
    Uses the existing six samples; no additional raytracing.
    This checks the interpolant at vertices, not the entire true mapping.
    """
    # At each vertex, estimate derivatives toward the next and
    # previous vertices in cyclic order. Using differences avoids
    # combining large absolute source-plane coordinates directly.
    d_next = 4.0 * (beta_m[:, [2, 0, 1]] - beta_v) - (beta_v[:, [1, 2, 0]] - beta_v)
    d_prev = 4.0 * (beta_m[:, [1, 2, 0]] - beta_v) - (beta_v[:, [2, 0, 1]] - beta_v)

    det = d_next[..., 0] * d_prev[..., 1] - d_next[..., 1] * d_prev[..., 0]

    # Cyclic lens-plane edge pairs have the same determinant.
    # Its common factor can be omitted when checking sign agreement.
    return backend.all(backend.isfinite(det), dim=1) & (
        backend.all(det > 0, dim=1) | backend.all(det < 0, dim=1)
    )


def evaluate_criterion(beta_v, beta_m, classes, level, h0, min_img_sep, pinv0, compose):
    """
    Steps 3 to 7 of the refinement criterion, vectorized over triangles.

    Step 4 (parity) is :func:`parity_from_children`; step 7 (deviation) catches
    curvature. Neither alone is sufficient.

    Parameters
    ----------
    beta_v: ndarray
        Source-plane vertices, shape ``(n, 3, 2)``.

        *Unit: arcsec*

    beta_m: ndarray
        Source-plane midpoints ``m1, m2, m3``, shape ``(n, 3, 2)``.

        *Unit: arcsec*

    classes: ndarray
        Orientation class of each triangle, shape ``(n,)`` int64.
    level: int
        Refinement level of the triangles.
    h0: float
        Level-0 cell size ``fov / init_res``.

        *Unit: arcsec*

    min_img_sep: float
        Lens-plane tolerance.

        *Unit: arcsec*

    pinv0: ndarray
        ``PINV0`` from :func:`child_matrix_tables`.
    compose: ndarray
        ``COMPOSE`` from :func:`child_matrix_tables`.

    Returns
    -------
    keep: ndarray
        ``(n,)`` bool, True where the triangle is converged and terminal.
    parity_ok: ndarray
        ``(n,)`` bool, True where ``sign(det Q_k)`` is constant over the children.
    s: ndarray
        ``(n,)`` float64, ``min_k sigma_min(A_k)``. Exactly ``0.0`` is legal and
        expected near a critical curve; it forces the split, and the size floor
        terminates the descent.
    """
    Q = child_shape_matrices(beta_v, beta_m)
    parity_ok = parity_from_children(Q) & quadratic_vertex_parity_ok(beta_v, beta_m)

    A = Q @ pinv0[compose[classes]]  # (n, 4, 2, 2), up to the common 2**(d+1)/h0
    s = backend.min(sigma_min_2x2(A), dim=1) * (2.0 ** (level + 1)) / h0

    r = midpoint_deviation(beta_v, beta_m)
    keep = parity_ok & converged_from_deviation(r, s, min_img_sep)
    return keep, parity_ok, s


# ---------------------------------------------------------------------------
# Query kernels (backend-dispatched)
# ---------------------------------------------------------------------------


def triangle_weights(tri, beta) -> ArrayLike:
    """
    The three cross products that give containment and barycentric coordinates.

    With ``q1, q2, q3`` the triangle's mapped vertices, ``w_i`` is the cross
    product of the two edges of the sub-triangle opposite vertex ``i``. Then
    ``w1 + w2 + w3 == d`` identically, where ``d`` is twice the signed area, so
    ``w / d`` sums to one by construction and no matrix inverse is needed.

    Because a mesh vertex is stored once and referenced by index, two leaves
    sharing an edge form these products from bit-identical operands in opposite
    order. IEEE multiplication is commutative, so their weights on that edge are
    **exactly** negated and a query point can never fall through the seam between
    them.

    Parameters
    ----------
    tri: ArrayLike
        Source-plane triangle vertices, shape ``(T, 3, 2)``.

        *Unit: arcsec*

    beta: ArrayLike
        Query points, one per candidate, shape ``(T, 2)``.

        *Unit: arcsec*

    Returns
    -------
    ArrayLike
        Shape ``(T, 3)``.
    """
    q1 = tri[:, 0, :] - beta
    q2 = tri[:, 1, :] - beta
    q3 = tri[:, 2, :] - beta
    return backend.stack(
        (
            q2[:, 0] * q3[:, 1] - q2[:, 1] * q3[:, 0],
            q3[:, 0] * q1[:, 1] - q3[:, 1] * q1[:, 0],
            q1[:, 0] * q2[:, 1] - q1[:, 1] * q2[:, 0],
        ),
        dim=-1,
    )


def contains(w) -> ArrayLike:
    """
    Containment test: all three weights share a sign, zeros counting as inside.

    Source-plane images flip handedness across critical curves by design, so a
    fixed positive convention would be wrong on half the mesh. Since
    ``w1 + w2 + w3 == d``, "all three share a sign" implies that sign is
    ``sign(d)`` whenever ``d != 0`` -- so this is equivalent to testing against the
    triangle's own ``d``, while also being well defined when ``d`` is *exactly*
    zero. That case is reachable: three source-plane vertices can be exactly
    collinear in floating point, and a ``kappa = 1`` sheet maps every leaf to a
    point. Testing against ``sign(d) == 0`` would make every such leaf a hit for
    every query.

    Zeros counting as inside means a point on a shared edge returns both leaves.
    That is intended, and is the main reason candidate count is not image
    multiplicity.

    Parameters
    ----------
    w: ArrayLike
        Weights from :func:`triangle_weights`, shape ``(T, 3)``.

    Returns
    -------
    ArrayLike
        Shape ``(T,)`` bool.
    """
    nonneg = (w[..., 0] >= 0) & (w[..., 1] >= 0) & (w[..., 2] >= 0)
    nonpos = (w[..., 0] <= 0) & (w[..., 1] <= 0) & (w[..., 2] <= 0)
    return nonneg | nonpos


def sanitize_bary(w, d) -> ArrayLike:
    """
    Normalize weights to barycentric coordinates, clamping then falling back.

    ``d`` goes to zero on leaves straddling a critical curve, so ``w / d`` there is
    a ratio of two quantities at the roundoff floor -- unbounded, possibly outside
    the triangle, or ``NaN``. Two regimes, handled in order.

    The clip handles ordinary roundoff: a hit passed containment, so
    ``bary in [0, 1]**3`` holds mathematically and small excursions are numerical
    only. The centroid branch handles genuine breakdown, where ``w`` and ``d`` are
    both noise and the clipped components carry no information; it is also the only
    defined answer when they clip to all-zero. ``isfinite`` is checked *after* the
    clip, because clipping propagates ``NaN``.

    The centroid is a bounded fallback, not a guess. A leaf with ``d`` near zero
    reached the size floor, so its longest edge is at most ``min_img_sep`` and the
    centroid is within ``(2/3) * l_max`` of every point in it.

    Parameters
    ----------
    w: ArrayLike
        Weights of the hits, shape ``(K, 3)``.
    d: ArrayLike
        Twice the signed source-plane area of each hit leaf, shape ``(K,)``.

    Returns
    -------
    ArrayLike
        Shape ``(K, 3)``, guaranteed to lie in the simplex.
    """
    bary = backend.clamp(w / backend.unsqueeze(d, -1), 0.0, 1.0)
    total = bary[..., 0] + bary[..., 1] + bary[..., 2]
    ok = (
        (total > 0)
        & backend.isfinite(bary[..., 0])
        & backend.isfinite(bary[..., 1])
        & backend.isfinite(bary[..., 2])
    )
    safe = backend.where(ok, total, backend.ones_like(total))
    normed = bary / backend.unsqueeze(safe, -1)
    third = backend.ones_like(bary) / 3
    return backend.where(backend.unsqueeze(ok, -1), normed, third)


# ---------------------------------------------------------------------------
# Dyadic lattice and build-argument validation
# ---------------------------------------------------------------------------

MAX_KEY = 2**63 - 1


def depth_floor(fov, init_res, min_img_sep) -> int:
    """
    Level at which the longest leaf edge first falls to ``min_img_sep``.

    Red refinement makes every child similar to its parent with ratio 1/2, so
    ``l_max`` is a function of level alone and the size floor is a depth computable
    up front. ``sqrt(2) * fov / init_res`` is the level-0 hypotenuse.
    """
    l_max0 = math.sqrt(2.0) * fov / init_res
    if l_max0 <= min_img_sep:
        return 0
    return int(math.ceil(math.log2(l_max0 / min_img_sep)))


def validate_build_args(
    fov, init_res, min_img_sep, max_depth, requested_min_img_sep=None
) -> None:
    """
    Reject impossible parameters, including a lattice that would overflow int64.

    ``min_img_sep`` is the value every check and the depth computation use.
    ``requested_min_img_sep`` names only the positivity message, so a caller who
    halved it (``build_adaptive_mesh``) is told the number they actually
    supplied rather than the halved one. Defaults to ``min_img_sep`` for a
    direct call, where the two coincide.
    """
    if requested_min_img_sep is None:
        requested_min_img_sep = min_img_sep
    if not fov > 0:
        raise ValueError(f"fov must be positive, got {fov}")
    if init_res < 1:
        raise ValueError(f"init_res must be at least 1, got {init_res}")
    if not min_img_sep > 0:
        raise ValueError(f"min_img_sep must be positive, got {requested_min_img_sep}")
    if max_depth < 0:
        raise ValueError(f"max_depth must be non-negative, got {max_depth}")
    max_level = min(max_depth, depth_floor(fov, init_res, min_img_sep))
    # One level finer than max_level: see `Lattice`. The guard has to size the
    # lattice actually built, not the finest triangle level.
    n = init_res * (1 << (max_level + 1))
    if (n + 1) ** 2 >= MAX_KEY:
        raise ValueError(
            f"lattice too fine to key in int64: init_res={init_res} at level "
            f"{max_level} needs a lattice of {n + 1} points per axis, one level "
            f"finer than max_level so that max_level edge midpoints are lattice "
            f"points. Raise min_img_sep, lower max_depth, or lower init_res."
        )


class Lattice(NamedTuple):
    """
    Dyadic integer lattice over the square domain, at the finest allowed level.

    Every mesh vertex is an integer pair, so midpoints are exact integer averages
    -- no float hashing, no rounding tolerance. The lens-plane position is a pure
    function of the integer pair, so two triangles sharing a vertex compute
    bit-identical coordinates. That is the root of the exact-negation property that
    stops a query falling through the seam between adjacent leaves.

    The lattice is built one level finer than ``max_level``, so a triangle's
    edge vectors are multiples of ``1 << (max_level + 1 - d)`` at level ``d``
    -- at least 2 for every ``d <= max_level``. That makes :func:`_midpoint_ij`
    exact at *every* level, ``max_level`` included, which is what lets the
    parity test run there.

    It also partitions the lattice. Every point the vertex cache holds -- a
    vertex at any level, or a midpoint below ``max_level`` -- has **even**
    coordinates; a ``max_level`` midpoint always has at least one **odd**
    coordinate. So the ``max_level`` midpoint pass can never re-trace a cached
    point, and a ``max_level`` midpoint can never be a triangle vertex.

    Widening does not move anything. ``fov / (2n)`` is exactly ``fl(fov / n) / 2``
    and ``(2 * ij) * (scale / 2)`` rounds the same exact real as ``ij * scale``,
    so every pre-existing point keeps a bit-identical position. Keys scale
    uniformly, so :func:`_canonical_order` is unchanged too.
    """

    level: int
    n: int
    stride: int
    scale: float
    lo: ArrayLike


def make_lattice(fov, x0, y0, init_res, lattice_level) -> Lattice:
    """
    Build a :class:`Lattice` covering ``fov``, centred at ``(x0, y0)``.

    Parameters
    ----------
    fov: float
        Field of view.

        *Unit: arcsec*

    x0: float
        Domain centre, x.

        *Unit: arcsec*

    y0: float
        Domain centre, y.

        *Unit: arcsec*

    init_res: int
        Level-0 grid resolution.
    lattice_level: int
        Level at which the lattice itself is built -- one finer than
        ``max_level``, see :class:`Lattice`.

    Returns
    -------
    Lattice
    """
    level = int(lattice_level)
    n = int(init_res) * (1 << level)
    stride = n + 1
    scale = float(fov) / n
    lo = backend.as_array([x0 - fov / 2.0, y0 - fov / 2.0], dtype=backend.float64)
    return Lattice(level=level, n=n, stride=stride, scale=scale, lo=lo)


def lattice_key(lat, ij):
    """Lattice key of integer coordinates, shape ``(..., 2) -> (...)``."""
    return ij[..., 0] * lat.stride + ij[..., 1]


def lattice_ij_from_key(lat, key):
    """Inverse of :func:`lattice_key`, shape ``(...) -> (..., 2)``."""
    return backend.stack((key // lat.stride, key % lat.stride), dim=-1)


def lattice_xy(lat, ij):
    """Lens-plane position, shape ``(..., 2) -> (..., 2)``.

    *Unit: arcsec*
    """
    return lat.lo + backend.to(ij, dtype=backend.float64) * lat.scale


def lattice_on_boundary(lat, ij):
    """True where the point lies on the edge of the domain."""
    return (
        (ij[..., 0] == 0)
        | (ij[..., 0] == lat.n)
        | (ij[..., 1] == 0)
        | (ij[..., 1] == lat.n)
    )


# ---------------------------------------------------------------------------
# Vertex cache and active-vertex set
# ---------------------------------------------------------------------------


class VertexCache(NamedTuple):
    """
    Lattice key to slot, with the source-plane image of every evaluated point.

    Lookup is ``backend.searchsorted`` against a sorted key array rather than
    a Python dict, so a whole level's worth of points resolves in one
    vectorized call. Slots are assigned monotonically in order of first
    evaluation and never move.

    ``ij`` and ``beta`` hold the lattice coordinates and source-plane image of
    every evaluated point, shape ``(N, 2)`` and indexed by slot. ``keys`` and
    ``slots`` are the sorted-key index: ``keys`` is ascending, and
    ``slots[i]`` is the slot of ``keys[i]``.
    """

    keys: ArrayLike
    slots: ArrayLike
    ij: ArrayLike
    beta: ArrayLike


def empty_cache(device=None) -> VertexCache:
    """An empty :class:`VertexCache`."""
    return VertexCache(
        keys=backend.empty((0,), dtype=backend.int64, device=device),
        slots=backend.empty((0,), dtype=backend.int64, device=device),
        ij=backend.empty((0, 2), dtype=backend.int64, device=device),
        beta=backend.empty((0, 2), dtype=backend.float64, device=device),
    )


def cache_size(cache) -> int:
    """Number of vertices held in the cache."""
    return int(cache.ij.shape[0])


def cache_lookup(cache, keys) -> ArrayLike:
    """Slot of each key, or ``-1`` where absent."""
    if cache.keys.shape[0] == 0:
        return backend.zeros_like(keys) - 1
    n = cache.keys.shape[0]
    pos = backend.clamp(backend.searchsorted(cache.keys, keys), 0, n - 1)
    return backend.where(cache.keys[pos] == keys, cache.slots[pos], -1)


def cache_missing(cache, keys) -> ArrayLike:
    """Unique keys not yet evaluated, ascending."""
    uniq = backend.unique(keys)
    return uniq[cache_lookup(cache, uniq) < 0]


def cache_insert(cache, keys, ij, beta) -> Tuple[VertexCache, ArrayLike]:
    """
    Assign slots to new keys. ``keys`` must be unique, absent, and sorted.

    The key index is merged rather than re-sorted. Both sides are already
    sorted -- ``keys`` comes from :func:`cache_missing`, which returns
    ``backend.unique`` output, and ``cache.keys`` is maintained sorted -- and
    no key appears on both sides, so ``searchsorted`` plus a running offset
    gives each new key its position in the merged array outright. The result
    is identical to sorting the concatenation, because with all keys distinct
    the sorted order is unique.

    Returns
    -------
    VertexCache
        The updated cache.
    ArrayLike
        The slots assigned to ``keys``, in the order given.
    """
    start = cache.ij.shape[0]
    k = int(keys.shape[0])
    slots = backend.arange(start, start + k, dtype=backend.int64)

    new_ij = backend.concatenate([cache.ij, ij], dim=0)
    new_beta = backend.concatenate([cache.beta, beta], dim=0)

    total = cache.keys.shape[0] + k
    dest = backend.searchsorted(cache.keys, keys) + backend.arange(
        k, dtype=backend.int64
    )
    new_keys = backend.fill_at_indices(
        backend.empty((total,), dtype=backend.int64), dest, keys
    )
    new_slots = backend.fill_at_indices(
        backend.empty((total,), dtype=backend.int64), dest, slots
    )
    # The complement of `dest`: where the pre-existing keys/slots land in the
    # merged array. Computed as a boolean mask, then converted to indices with
    # `flatnonzero` so the merge only ever calls `fill_at_indices` with
    # integer positions.
    stay = backend.fill_at_indices(
        backend.ones((total,), dtype=backend.bool), dest, False
    )
    old_dest = backend.flatnonzero(stay)
    new_keys = backend.fill_at_indices(new_keys, old_dest, cache.keys)
    new_slots = backend.fill_at_indices(new_slots, old_dest, cache.slots)

    return (
        VertexCache(keys=new_keys, slots=new_slots, ij=new_ij, beta=new_beta),
        slots,
    )


def empty_active(device=None) -> ArrayLike:
    """
    Lattice points that are currently vertices of some triangle in the mesh.

    Stored as one flag per **vertex-cache slot**, not as a sorted key set.
    Every active key is by construction a vertex of some triangle, so it has
    already been evaluated and is already in the cache -- a second sorted
    structure would duplicate the cache's own key index, and keeping it
    sorted cost an ``np.union1d`` over the whole active set on every
    insertion, which was the single largest term in the build.

    Separate from the vertex cache, which also holds midpoints of
    tested-but-never-split triangles. Only ever grows, since a parent's
    vertices are inherited by all its children.
    """
    return backend.zeros((0,), dtype=backend.bool, device=device)


def active_add_slots(active, n_slots, slots) -> ArrayLike:
    """
    Activate vertex-cache slots.

    Takes slots rather than keys because every caller already holds them:
    re-keying a triangle's vertices only to look them up again is exactly the
    work this function exists to avoid.
    """
    # Trip-wire for the `active subset of cache` invariant. A -1 slot -- what
    # `cache_lookup` returns for an absent key -- would negative-index into
    # the last cache entry and activate the wrong vertex, and the mesh would
    # come out unbalanced rather than raising.
    #
    # `raise AssertionError` rather than a bare `assert`: `python -O` strips
    # bare asserts, and this guards against silent geometric corruption.
    if not bool(backend.all(slots >= 0)):
        raise AssertionError("cannot activate an uncached vertex")
    # Concatenate unconditionally, even when `extra` is 0, so this always
    # scatters into a fresh array and never the caller's own. `torch.cat`/
    # `jnp.concatenate` both always allocate, unlike `fill_at_indices` on its
    # own: torch mutates its first argument in place and returns it, so
    # scattering directly into `active` on the no-growth path would silently
    # clobber the caller's array under torch while leaving it untouched under
    # jax -- the exact backend-divergence `cache_insert` avoids by always
    # writing into a fresh `backend.empty`/`backend.ones` buffer.
    extra = max(n_slots - active.shape[0], 0)
    active = backend.concatenate(
        [active, backend.zeros((extra,), dtype=backend.bool)], dim=0
    )
    return backend.fill_at_indices(active, slots, True)


def active_contains_slots(active, slots) -> ArrayLike:
    """True where the slot is an active vertex. ``-1`` reads as False."""
    if active.shape[0] == 0:
        return backend.zeros(slots.shape, dtype=backend.bool)
    present = slots >= 0
    return present & active[backend.where(present, slots, 0)]


def active_contains(active, cache, keys) -> ArrayLike:
    """
    True where the key is an active vertex.

    A key absent from the cache was never evaluated, so it cannot be a
    triangle vertex and cannot be active -- ``cache_lookup`` returns ``-1``
    and :func:`active_contains_slots` reads that as False.
    """
    return active_contains_slots(active, cache_lookup(cache, keys))


# ---------------------------------------------------------------------------
# Leaf store
# ---------------------------------------------------------------------------

# Why a terminal leaf stopped refining. Plain ints, not an ``IntEnum``:
# ``status`` lives in a ``backend.int64`` array and is compared, scattered
# and broadcast through backend ops the whole way, which a NumPy-flavoured
# enum would fight at every one of those call sites for no benefit.
#
# ``LEAF_FORCED`` is distinct from ``LEAF_CONVERGED`` because a forced child
# carries no criterion evidence at all -- that is exactly what auto-converging
# decides -- so a caller auditing coverage must be able to tell them apart.
# Closure triangles have no status of their own; they inherit their origin's.
#
# ``LEAF_INVALID`` has three sources, all of them at ``max_level`` or later. A
# non-finite triangle is split unconditionally, so it can only come to rest at
# ``max_level``, where no split is left. A ``max_level`` triangle whose four
# hypothetical children do not share ``sign(det Q_k)`` straddles a fold at a
# scale the mesh cannot resolve, and is condemned rather than answering
# queries with a non-injective affine model. And nonfinite-origin propagation
# at freeze time is the third source. All three bound the coverage hole by
# the ``max_level`` leaf size rather than by ``fov / init_res``.
LEAF_CONVERGED = 0
LEAF_SIZE_FLOOR = 1
LEAF_FORCED = 2
LEAF_INVALID = 3
LEAF_NONFINITE = 4


class LeafStore(NamedTuple):
    """
    Terminal triangles, keyed by row index with a validity flag.

    Not append-only: a triangle marked converged at level ``d`` can be
    removed and replaced by descendants several levels later, when a distant
    refinement cascades back to it. Hence the flag and the single compaction
    at the end (:func:`store_compact`), rather than streaming into a flat
    array as we go.

    ``v`` holds the three vertex-cache slots of each leaf, shape ``(N, 3)``.
    ``level``, ``cls``, ``status`` and ``valid`` are per-row, shape ``(N,)``.
    ``status`` is ``backend.int64`` -- see the ``LEAF_*`` constants above.
    """

    v: ArrayLike
    level: ArrayLike
    cls: ArrayLike
    status: ArrayLike
    valid: ArrayLike


def empty_store(device=None) -> LeafStore:
    """An empty :class:`LeafStore`."""
    return LeafStore(
        v=backend.empty((0, 3), dtype=backend.int64, device=device),
        level=backend.empty((0,), dtype=backend.int64, device=device),
        cls=backend.empty((0,), dtype=backend.int64, device=device),
        status=backend.empty((0,), dtype=backend.int64, device=device),
        valid=backend.empty((0,), dtype=backend.bool, device=device),
    )


def _broadcast_row_field(value, n_rows) -> ArrayLike:
    """A per-row array as-is, or a Python scalar broadcast to ``n_rows``."""
    if hasattr(value, "shape"):
        return value
    return backend.zeros((n_rows,), dtype=backend.int64) + value


def store_add(store, v, level, cls, status) -> Tuple[LeafStore, ArrayLike]:
    """
    Append triangles, returning their row indices.

    ``level``, ``cls`` and ``status`` may each be a Python scalar or a
    per-row array; a scalar is broadcast to the row count before
    concatenating.

    Returns
    -------
    LeafStore
        The updated store.
    ArrayLike
        The row indices assigned to ``v``, in the order given.
    """
    start = store.v.shape[0]
    k = v.shape[0]
    rows = backend.arange(start, start + k, dtype=backend.int64)

    new_store = LeafStore(
        v=backend.concatenate([store.v, v], dim=0),
        level=backend.concatenate([store.level, _broadcast_row_field(level, k)], dim=0),
        cls=backend.concatenate([store.cls, _broadcast_row_field(cls, k)], dim=0),
        status=backend.concatenate(
            [store.status, _broadcast_row_field(status, k)], dim=0
        ),
        valid=backend.concatenate(
            [store.valid, backend.ones((k,), dtype=backend.bool)], dim=0
        ),
    )
    return new_store, rows


def store_remove(store, rows) -> LeafStore:
    """
    Mark rows invalid, returning a NEW store; ``store`` itself is untouched.

    Scatters into a copy of ``store.valid`` rather than ``store.valid``
    itself: ``backend.fill_at_indices`` mutates its first argument in place
    and returns it under torch, so writing straight into ``store.valid``
    would silently clobber the input store's own array under torch while
    leaving it (and every alias of it a caller might still hold) untouched
    under jax -- the same backend divergence :func:`cache_insert` and
    :func:`active_add_slots` avoid by always writing into a fresh buffer.
    """
    valid = backend.fill_at_indices(backend.copy(store.valid), rows, False)
    return LeafStore(
        v=store.v, level=store.level, cls=store.cls, status=store.status, valid=valid
    )


def store_compact(store) -> Tuple[ArrayLike, ArrayLike, ArrayLike, ArrayLike]:
    """The surviving rows of ``v``, ``level``, ``cls`` and ``status``."""
    keep = backend.flatnonzero(store.valid)
    return store.v[keep], store.level[keep], store.cls[keep], store.status[keep]


# ---------------------------------------------------------------------------
# Triangle helpers and 2:1 balance detection
# ---------------------------------------------------------------------------


def initial_triangles(
    init_res, lattice_level, root_class
) -> Tuple[ArrayLike, ArrayLike]:
    """
    Level-0 triangles: two per cell, split on the ``(0,0)-(1,1)`` diagonal.

    Both are emitted positively oriented. ``func/base.py`` builds its pair with
    *opposite* handedness; this fixes that so orientation is globally consistent
    and downstream degree or winding-number arguments stay available.

    Built with a ``backend.meshgrid(..., indexing="ij")`` cell grid, flattened
    in the same row-major order ``numpy`` uses -- the oracle test compares the
    result element by element, so a transposed ordering fails loudly rather
    than quietly.

    Parameters
    ----------
    init_res: int
        Level-0 grid resolution.
    lattice_level: int
        Level the lattice is built at -- one finer than ``max_level``, see
        :class:`Lattice`.
    root_class: ArrayLike
        ``ROOT_CLASS`` from :func:`child_matrix_tables`, shape ``(2,)``.

    Returns
    -------
    ij: ArrayLike
        ``(2 * init_res**2, 3, 2)`` int64 lattice coordinates.
    cls: ArrayLike
        ``(2 * init_res**2,)`` int64 orientation classes.
    """
    step = 1 << int(lattice_level)
    axis = backend.arange(init_res, dtype=backend.int64)
    i, j = backend.meshgrid(axis, axis, indexing="ij")
    base = backend.stack((i.reshape(-1), j.reshape(-1)), dim=-1) * step  # (r**2, 2)
    blocks, classes = [], []
    for s, shape in enumerate(ROOT_SHAPES):
        offs = backend.as_array(shape, dtype=backend.int64) * step  # (3, 2)
        blocks.append(base[:, None, :] + offs[None, :, :])
        classes.append(
            backend.zeros((base.shape[0],), dtype=backend.int64) + root_class[s]
        )
    return backend.concatenate(blocks, dim=0), backend.concatenate(classes, dim=0)


def midpoint_ij(ij) -> ArrayLike:
    """
    Edge midpoints ``m1, m2, m3``, with ``m_i`` opposite ``theta_i``.

    Exact integer averaging via integer ``//``: the lattice is one level finer
    than ``max_level`` (see :class:`Lattice`), so the coordinate sums are even
    at every level up to and including ``max_level``.

    Parameters
    ----------
    ij: ArrayLike
        Triangle vertex coordinates, shape ``(n, 3, 2)`` int64.

    Returns
    -------
    ArrayLike
        Shape ``(n, 3, 2)`` int64.
    """
    return backend.stack(
        (
            (ij[:, 1] + ij[:, 2]) // 2,
            (ij[:, 2] + ij[:, 0]) // 2,
            (ij[:, 0] + ij[:, 1]) // 2,
        ),
        dim=1,
    )


def red_split(v, m, cls, compose) -> Tuple[ArrayLike, ArrayLike]:
    """
    Split into the four canonical children, triangle-major.

    Parameters
    ----------
    v: ArrayLike
        Triangle vertex slots, shape ``(n, 3)`` int64.
    m: ArrayLike
        Edge-midpoint slots ``m1, m2, m3``, shape ``(n, 3)`` int64.
    cls: ArrayLike
        Orientation class of each triangle, shape ``(n,)`` int64.
    compose: ArrayLike
        ``COMPOSE`` from :func:`child_matrix_tables`, shape ``(6, 4)``.

    Returns
    -------
    child_v: ArrayLike
        ``(4n, 3)`` vertex slots, ordered as all four children of triangle 0,
        then triangle 1, and so on.
    child_cls: ArrayLike
        ``(4n,)`` orientation classes, in the same order.
    """
    six = backend.concatenate([v, m], dim=1)  # (n, 6)
    child_v = six[:, _CHILD_VERTEX_INDEX_TABLE].reshape(-1, 3)
    child_cls = compose[cls].reshape(-1)
    return child_v, child_cls


def edge_quarter_keys(lat, ij) -> ArrayLike:
    """
    Keys of both quarter points on each of the three edges.

    A neighbour across an edge that is two or more levels finer has one of
    these as a vertex, so six hash lookups decide balance for a triangle --
    no edge-to-triangle adjacency table and no ancestry walk. Both quarter
    points are checked because the neighbour across an edge can itself be
    non-uniform.

    The caller must only pass triangles at level ``<= max_level - 2``, where
    the edge vectors are divisible by four and the quarter points are lattice
    points.

    Parameters
    ----------
    lat: Lattice
        Used to key the quarter points.
    ij: ArrayLike
        Lattice coordinates, shape ``(n, 3, 2)`` int64.

    Returns
    -------
    ArrayLike
        Shape ``(n, 6)`` int64.
    """
    a = ij[:, [0, 1, 2], :]
    b = ij[:, [1, 2, 0], :]
    delta = (b - a) // 4
    return backend.concatenate(
        (lattice_key(lat, a + delta), lattice_key(lat, b - delta)), dim=1
    )


def find_unbalanced(store, cache, lat, active, max_level, frontier_level) -> ArrayLike:
    """
    Rows of ``store`` carrying an active quarter point on some edge.

    Two independent level bounds apply. ``level <= frontier_level - 2`` is an
    optimization: only triangles at least two levels coarser than the
    frontier can have been invalidated by it, so the scan skips most of the
    store. ``level <= max_level - 2`` is the bound above which no neighbour
    can be two levels finer, since ``max_level`` is the finest level there is.

    Parameters
    ----------
    store: LeafStore
        Terminal triangles; only rows with ``valid`` set are scanned.
    cache: VertexCache
        Supplies the lattice coordinates of each row's vertices.
    lat: Lattice
        Used to key the quarter points.
    active: ArrayLike
        Pre-existing active-vertex set; membership decides a violation.
    max_level: int
        Finest allowed level.
    frontier_level: int
        Level of the finest triangles created in the current round.

    Returns
    -------
    ArrayLike
        Int64 indices into ``store``'s rows.
    """
    # `frontier_level <= max_level` holds for every call the level loop
    # makes, so the first term always binds and the second is unreachable
    # defensive code today. Keep the min(): `max_level - 2` is the level
    # above which no neighbour can be two levels finer, since `max_level` is
    # the finest level there is. (It used to double as an integrality
    # requirement for the quarter-point arithmetic below; on the widened
    # lattice quarter points stay lattice points down to `max_level - 1`, so
    # that role is gone and only the balance argument remains.)
    bound = min(frontier_level - 2, max_level - 2)
    cand = backend.flatnonzero(store.valid & (store.level <= bound))
    if cand.shape[0] == 0:
        return cand
    ij = cache.ij[store.v[cand]]  # (n, 3, 2)
    # One edge at a time, accumulating into a single `(n,)` mask, rather than
    # building the whole `(cand, 6)` key array the way `edge_quarter_keys`
    # does: the batched form held 153 MB at a million leaves -- the largest
    # transient in the level loop. The disjunction is over the same six keys
    # `edge_quarter_keys` returns; only the association changes.
    hit = backend.zeros((cand.shape[0],), dtype=backend.bool)
    for e in range(3):
        a = ij[:, e, :]
        b = ij[:, (e + 1) % 3, :]
        delta = (b - a) // 4
        for quarter in (a + delta, b - delta):
            hit = hit | active_contains(active, cache, lattice_key(lat, quarter))
    return cand[hit]
