"""
Pure kernels for the adaptive lens-plane mesh.

This module has two clearly separated halves.

**Host-side build kernels** operate on ``numpy`` float64 arrays. The mesh build is
a host-side algorithm whose only array-API contact is the ``raytrace`` callback, so
these deliberately do not use ``backend``. Keeping them in one numerical world is
what makes the ``NaN`` semantics of :func:`sigma_min_2x2` and
:func:`converged_from_deviation` verifiable.

**Query kernels** operate on ``backend`` arrays and are used by ``Mesh.query``.
"""

from typing import Tuple

import numpy as np

__all__ = (
    "CHILD_VERTEX_INDICES",
    "ROOT_SHAPES",
    "shape_matrix",
    "child_matrix_tables",
    "affine_from_triangles",
)

# ---------------------------------------------------------------------------
# Host-side build kernels (numpy, float64)
# ---------------------------------------------------------------------------

# Indices into the stacked six-point array [theta1, theta2, theta3, m1, m2, m3]
# giving the four children in the orientation-preserving order
#   C_1 = (t1, m3, m2)  C_2 = (t2, m1, m3)  C_3 = (t3, m2, m1)  C_4 = (m1, m2, m3)
# with m_i the midpoint opposite theta_i.
CHILD_VERTEX_INDICES = ((0, 5, 4), (1, 3, 5), (2, 4, 3), (3, 4, 5))

# The two triangles splitting the unit cell along the (0,0)-(1,1) diagonal, both
# positively oriented. Note ``func/base.py`` builds its pair with *opposite*
# handedness; this module fixes that so orientation is globally consistent.
ROOT_SHAPES = (
    ((0, 0), (1, 1), (0, 1)),
    ((0, 0), (1, 0), (1, 1)),
)


def shape_matrix(tri):
    """
    Edge matrix ``P = [v1 - v0 | v2 - v0]`` of a triangle.

    Parameters
    ----------
    tri: ndarray
        Triangle vertices, shape ``(..., 3, 2)``.

        *Unit: arcsec*

    Returns
    -------
    ndarray
        Shape ``(..., 2, 2)``, the two edge vectors as columns.
    """
    return np.stack(
        (tri[..., 1, :] - tri[..., 0, :], tri[..., 2, :] - tri[..., 0, :]), axis=-1
    )


def affine_from_triangles(p, q):
    """
    Linear part of the affine map reproducing three vertex correspondences.

    Invariant under any relabelling applied simultaneously to both triangles,
    which is what makes the parity test immune to vertex ordering.

    Parameters
    ----------
    p: ndarray
        Lens-plane triangle, shape ``(..., 3, 2)``.
    q: ndarray
        Source-plane triangle, shape ``(..., 3, 2)``.

    Returns
    -------
    ndarray
        Shape ``(..., 2, 2)``.
    """
    return shape_matrix(q) @ np.linalg.inv(shape_matrix(p))


def _derive_child_matrices():
    """Recover ``M_k`` from the child ordering, where ``P_k = (1/2) P M_k``."""
    parent = np.array([[0.0, 0.0], [3.0, 2.0], [-1.0, 5.0]])
    t1, t2, t3 = parent
    six = np.stack([t1, t2, t3, (t2 + t3) / 2, (t3 + t1) / 2, (t1 + t2) / 2])
    P = shape_matrix(parent)
    M = np.empty((4, 2, 2), dtype=np.int64)
    for k, idx in enumerate(CHILD_VERTEX_INDICES):
        Pk = shape_matrix(six[list(idx)])
        exact = 2.0 * np.linalg.solve(P, Pk)
        M[k] = np.rint(exact).astype(np.int64)
        if not np.allclose(exact, M[k], atol=1e-9):
            raise AssertionError("child matrices are not integral")
    return M


def child_matrix_tables() -> (
    Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray]
):
    """
    Fixed tables for red refinement.

    Red refinement gives ``P_k = (1/2) P M_k`` with ``M_k`` a fixed integer matrix
    per child index, so by induction ``P`` at level ``d`` is ``2**-d * h0 * R @ G[c]``
    for one of finitely many group elements ``G[c]``. The group generated by the four
    ``M_k`` is ``{+-I, +-M_2, +-M_3}``, of order six, and both root shapes lie in a
    single orbit -- so the inverse table has exactly six entries, not one per level.

    Returns
    -------
    M: ndarray
        ``(4, 2, 2)`` int64 child matrices; every ``det M_k == +1``.
    G: ndarray
        ``(6, 2, 2)`` int64 group elements in canonical order.
    COMPOSE: ndarray
        ``(6, 4)`` int64 with ``G[COMPOSE[c, k]] == G[c] @ M[k]``.
    PINV0: ndarray
        ``(6, 2, 2)`` float64 with ``PINV0[c] == inv(R @ G[c])``, ``R`` the class-0
        root shape. A triangle of class ``c`` at level ``d`` has
        ``inv(P_child_k) == (2**(d + 1) / h0) * PINV0[COMPOSE[c, k]]``.
    ROOT_CLASS: ndarray
        ``(2,)`` int64 class index of each entry of :data:`ROOT_SHAPES`.
    """
    M = _derive_child_matrices()
    eye = np.eye(2, dtype=np.int64)
    G = np.stack([eye, M[1], M[2], -eye, -M[1], -M[2]])

    lookup = {G[c].tobytes(): c for c in range(6)}
    COMPOSE = np.empty((6, 4), dtype=np.int64)
    for c in range(6):
        for k in range(4):
            product = (G[c] @ M[k]).astype(np.int64)
            if product.tobytes() not in lookup:
                raise AssertionError("child matrix group is not closed")
            COMPOSE[c, k] = lookup[product.tobytes()]

    R = shape_matrix(np.asarray(ROOT_SHAPES[0], dtype=np.float64))
    PINV0 = np.stack([np.linalg.inv(R @ G[c].astype(np.float64)) for c in range(6)])

    ROOT_CLASS = np.empty(2, dtype=np.int64)
    for s, shape in enumerate(ROOT_SHAPES):
        target = shape_matrix(np.asarray(shape, dtype=np.float64))
        for c in range(6):
            if np.allclose(R @ G[c].astype(np.float64), target):
                ROOT_CLASS[s] = c
                break
        else:  # pragma: no cover - guarded by test_group_tables_close_...
            raise AssertionError(f"root shape {s} is not in the orbit of R")
    return M, G, COMPOSE, PINV0, ROOT_CLASS
