"""
Pure kernels for the adaptive lens-plane mesh.

This module has two clearly separated halves.

**Host-side build kernels** operate on ``numpy`` float64 arrays. The mesh build is
a host-side algorithm whose only array-API contact is the ``raytrace`` callback, so
these deliberately do not use ``backend``. Keeping them in one numerical world is
what makes the ``NaN`` semantics of :func:`sigma_min_2x2` and
:func:`converged_from_deviation` verifiable.

**Query kernels** operate on ``backend`` arrays and are used by ``Mesh.query``.
"""

from typing import Tuple

import numpy as np

from ...backend_obj import ArrayLike, backend

__all__ = (
    "CHILD_VERTEX_INDICES",
    "ROOT_SHAPES",
    "shape_matrix",
    "child_matrix_tables",
    "affine_from_triangles",
    "sigma_min_2x2",
    "midpoint_deviation",
    "converged_from_deviation",
    "evaluate_criterion",
    "triangle_weights",
    "contains",
    "sanitize_bary",
)

# ---------------------------------------------------------------------------
# Host-side build kernels (numpy, float64)
# ---------------------------------------------------------------------------

# Indices into the stacked six-point array [theta1, theta2, theta3, m1, m2, m3]
# giving the four children in the orientation-preserving order
#   C_1 = (t1, m3, m2)  C_2 = (t2, m1, m3)  C_3 = (t3, m2, m1)  C_4 = (m1, m2, m3)
# with m_i the midpoint opposite theta_i.
CHILD_VERTEX_INDICES = ((0, 5, 4), (1, 3, 5), (2, 4, 3), (3, 4, 5))

# The two triangles splitting the unit cell along the (0,0)-(1,1) diagonal, both
# positively oriented. Note ``func/base.py`` builds its pair with *opposite*
# handedness; this module fixes that so orientation is globally consistent.
ROOT_SHAPES = (
    ((0, 0), (1, 1), (0, 1)),
    ((0, 0), (1, 0), (1, 1)),
)


def shape_matrix(tri):
    """
    Edge matrix ``P = [v1 - v0 | v2 - v0]`` of a triangle.

    Parameters
    ----------
    tri: ndarray
        Triangle vertices, shape ``(..., 3, 2)``.

        *Unit: arcsec*

    Returns
    -------
    ndarray
        Shape ``(..., 2, 2)``, the two edge vectors as columns.

        *Unit: arcsec*
    """
    return np.stack(
        (tri[..., 1, :] - tri[..., 0, :], tri[..., 2, :] - tri[..., 0, :]), axis=-1
    )


def affine_from_triangles(p, q):
    """
    Linear part of the affine map reproducing three vertex correspondences.

    Invariant under any relabelling applied simultaneously to both triangles,
    which is what makes the parity test immune to vertex ordering.

    Parameters
    ----------
    p: ndarray
        Lens-plane triangle, shape ``(..., 3, 2)``.

        *Unit: arcsec*

    q: ndarray
        Source-plane triangle, shape ``(..., 3, 2)``.

        *Unit: arcsec*

    Returns
    -------
    ndarray
        Shape ``(..., 2, 2)``.
    """
    return shape_matrix(q) @ np.linalg.inv(shape_matrix(p))


def _derive_child_matrices():
    """Recover ``M_k`` from the child ordering, where ``P_k = (1/2) P M_k``."""
    parent = np.array([[0.0, 0.0], [3.0, 2.0], [-1.0, 5.0]])
    t1, t2, t3 = parent
    six = np.stack([t1, t2, t3, (t2 + t3) / 2, (t3 + t1) / 2, (t1 + t2) / 2])
    P = shape_matrix(parent)
    M = np.empty((4, 2, 2), dtype=np.int64)
    for k, idx in enumerate(CHILD_VERTEX_INDICES):
        Pk = shape_matrix(six[list(idx)])
        exact = 2.0 * np.linalg.solve(P, Pk)
        M[k] = np.rint(exact).astype(np.int64)
        if not np.allclose(exact, M[k], atol=1e-9):
            raise AssertionError("child matrices are not integral")
    return M


def child_matrix_tables() -> (
    Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray]
):
    """
    Fixed tables for red refinement.

    Red refinement gives ``P_k = (1/2) P M_k`` with ``M_k`` a fixed integer matrix
    per child index, so by induction ``P`` at level ``d`` is ``2**-d * h0 * R @ G[c]``
    for one of finitely many group elements ``G[c]``. The group generated by the four
    ``M_k`` is ``{+-I, +-M_2, +-M_3}``, of order six, and both root shapes lie in a
    single orbit -- so the inverse table has exactly six entries, not one per level.

    Returns
    -------
    M: ndarray
        ``(4, 2, 2)`` int64 child matrices; every ``det M_k == +1``.
    G: ndarray
        ``(6, 2, 2)`` int64 group elements in canonical order.
    COMPOSE: ndarray
        ``(6, 4)`` int64 with ``G[COMPOSE[c, k]] == G[c] @ M[k]``.
    PINV0: ndarray
        ``(6, 2, 2)`` float64 with ``PINV0[c] == inv(R @ G[c])``, ``R`` the class-0
        root shape. A triangle of class ``c`` at level ``d`` has
        ``inv(P_child_k) == (2**(d + 1) / h0) * PINV0[COMPOSE[c, k]]``.
    ROOT_CLASS: ndarray
        ``(2,)`` int64 class index of each entry of :data:`ROOT_SHAPES`.
    """
    M = _derive_child_matrices()
    eye = np.eye(2, dtype=np.int64)
    G = np.stack([eye, M[1], M[2], -eye, -M[1], -M[2]])

    lookup = {G[c].tobytes(): c for c in range(6)}
    COMPOSE = np.empty((6, 4), dtype=np.int64)
    for c in range(6):
        for k in range(4):
            product = (G[c] @ M[k]).astype(np.int64)
            if product.tobytes() not in lookup:
                raise AssertionError("child matrix group is not closed")
            COMPOSE[c, k] = lookup[product.tobytes()]

    R = shape_matrix(np.asarray(ROOT_SHAPES[0], dtype=np.float64))
    PINV0 = np.stack([np.linalg.inv(R @ G[c].astype(np.float64)) for c in range(6)])

    ROOT_CLASS = np.empty(2, dtype=np.int64)
    for s, shape in enumerate(ROOT_SHAPES):
        target = shape_matrix(np.asarray(shape, dtype=np.float64))
        for c in range(6):
            if np.allclose(R @ G[c].astype(np.float64), target):
                ROOT_CLASS[s] = c
                break
        else:  # pragma: no cover - guarded by test_group_tables_close_...
            raise AssertionError(f"root shape {s} is not in the orbit of R")
    return M, G, COMPOSE, PINV0, ROOT_CLASS


def sigma_min_2x2(A):
    """
    Smallest singular value of a batch of 2x2 matrices, in closed form.

    Pulling a source-plane displacement back to the lens plane gives
    ``||dtheta|| <= ||dbeta|| / sigma_min(A)``, so ``sigma_min`` is the correct
    anisotropic contraction scale. ``det A = sigma_min * sigma_max`` conflates the
    two directions and is wrong near folds, where ``sigma_min -> 0`` while
    ``sigma_max`` stays order one.

    With ``F = ||A||_F**2`` and ``D = |det A|``, ``(sigma_max +- sigma_min)**2 =
    F +- 2D``. ``F - 2D >= 0`` holds in exact arithmetic but **not** in floating
    point -- for a near-conformal ``A`` it goes negative by an ulp, and the
    unguarded ``sqrt`` then returns ``NaN`` for the near-circularly-symmetric core
    of essentially every lens model. Hence the clip.

    ``sigma_min`` is returned as ``D / sigma_max`` rather than
    ``(sqrt(F + 2D) - sqrt(F - 2D)) / 2`` because the former is stable in the
    near-degenerate limit, which is exactly the near-caustic regime that drives
    refinement.

    The ``sigma_max == 0`` branch is exact, not a tolerance: ``sigma_max == 0`` iff
    ``A == 0``, whose smallest singular value is exactly zero. Do not replace it
    with ``max(sigma_min, eps)`` -- both ``np.maximum`` and ``torch.clamp``
    propagate ``NaN``, so a floor would fail open.

    Parameters
    ----------
    A: ndarray
        Shape ``(..., 2, 2)``, float64.

    Returns
    -------
    ndarray
        Shape ``(...)``. Exactly ``0.0`` where ``A == 0``; ``NaN`` where ``A`` is
        non-finite, so that step 7 fails closed.
    """
    F = (A**2).sum(axis=(-2, -1))
    D = np.abs(A[..., 0, 0] * A[..., 1, 1] - A[..., 0, 1] * A[..., 1, 0])
    sigma_max = (np.sqrt(F + 2 * D) + np.sqrt(np.clip(F - 2 * D, 0.0, None))) / 2
    zero = sigma_max == 0
    # Double `where` keeps the division away from 0/0 without masking a NaN input:
    # a NaN sigma_max fails the `== 0` test, so NaN reaches the output.
    return np.where(zero, 0.0, D / np.where(zero, 1.0, sigma_max))


def midpoint_deviation(beta_v, beta_m):
    """
    Distance between each mapped edge midpoint and its affine prediction.

    With ``m_i`` opposite ``theta_i``, the predicted image of ``m_i`` under an
    affine map is the mean of the two ``beta`` values at the endpoints of the edge
    it bisects, ``(beta_j + beta_k) / 2`` for cyclic ``(i, j, k)``.

    Parameters
    ----------
    beta_v: ndarray
        Source-plane vertices, shape ``(n, 3, 2)``.

        *Unit: arcsec*

    beta_m: ndarray
        Source-plane edge midpoints ``m1, m2, m3``, shape ``(n, 3, 2)``.

        *Unit: arcsec*

    Returns
    -------
    ndarray
        Shape ``(n, 3)``, a source-plane length.

        *Unit: arcsec*
    """
    predicted = 0.5 * (beta_v[:, [1, 2, 0], :] + beta_v[:, [2, 0, 1], :])
    return np.linalg.norm(predicted - beta_m, axis=-1)


def converged_from_deviation(r, s, min_img_sep):
    """
    Step 7 of the refinement criterion.

    Written as ``all(r < threshold)`` and never as ``not any(r >= threshold)``.
    The two are not equivalent when ``s`` is ``NaN``: under IEEE every comparison
    against ``NaN`` is False, so the ``>=`` form would mark a maximally degenerate
    triangle *converged*, silently inverting the intended behaviour. The ``<`` form
    puts ``NaN`` in the split branch. It also settles the exact-equality edge -- an
    affine-but-singular triangle (``r == 0``, ``s == 0``) gives ``0 < 0``, False,
    and splits, which is the conservative direction.

    Note the comparison is evaluated in the **source plane**: ``r`` is a
    source-plane length and ``s`` is dimensionless, so ``s * min_img_sep`` converts
    the lens-plane tolerance ``min_img_sep`` into a source-plane one. The
    equivalent lens-plane form ``r / s < min_img_sep`` must not be used, because
    dividing by ``s`` breaks on the legal and expected ``s == 0``.

    Parameters
    ----------
    r: ndarray
        Midpoint deviations, shape ``(n, 3)``.

        *Unit: arcsec*

    s: ndarray
        Smallest singular value over the four children, shape ``(n,)``.
    min_img_sep: float
        Lens-plane tolerance.

        *Unit: arcsec*

    Returns
    -------
    ndarray
        Shape ``(n,)`` bool.
    """
    return (r < (s * min_img_sep)[:, None]).all(axis=1)


def evaluate_criterion(beta_v, beta_m, classes, level, h0, min_img_sep, pinv0, compose):
    """
    Steps 3 to 7 of the refinement criterion, vectorized over triangles.

    Step 4 (parity) catches folds; step 7 (deviation) catches curvature. Neither
    alone is sufficient. The parity test needs no ``P`` at all: ``sign(det A_k) =
    sign(det Q_k) * sign(det P_k)`` and all four children share the parent's
    ``sign(det P_k)`` because every ``det M_k == +1``, so constancy of
    ``sign(det A_k)`` over ``k`` is equivalent to constancy of ``sign(det Q_k)``.

    Parameters
    ----------
    beta_v: ndarray
        Source-plane vertices, shape ``(n, 3, 2)``.

        *Unit: arcsec*

    beta_m: ndarray
        Source-plane midpoints ``m1, m2, m3``, shape ``(n, 3, 2)``.

        *Unit: arcsec*

    classes: ndarray
        Orientation class of each triangle, shape ``(n,)`` int64.
    level: int
        Refinement level of the triangles.
    h0: float
        Level-0 cell size ``fov / init_res``.

        *Unit: arcsec*

    min_img_sep: float
        Lens-plane tolerance.

        *Unit: arcsec*

    pinv0: ndarray
        ``PINV0`` from :func:`child_matrix_tables`.
    compose: ndarray
        ``COMPOSE`` from :func:`child_matrix_tables`.

    Returns
    -------
    keep: ndarray
        ``(n,)`` bool, True where the triangle is converged and terminal.
    parity_ok: ndarray
        ``(n,)`` bool, True where ``sign(det Q_k)`` is constant over the children.
    s: ndarray
        ``(n,)`` float64, ``min_k sigma_min(A_k)``. Exactly ``0.0`` is legal and
        expected near a critical curve; it forces the split, and the size floor
        terminates the descent.
    """
    stacked = np.concatenate([beta_v, beta_m], axis=1)  # (n, 6, 2)
    idx = np.asarray(CHILD_VERTEX_INDICES)  # (4, 3)
    q1 = stacked[:, idx[:, 0], :]
    q2 = stacked[:, idx[:, 1], :]
    q3 = stacked[:, idx[:, 2], :]
    Q = np.stack((q2 - q1, q3 - q1), axis=-1)  # (n, 4, 2, 2)

    det_q = Q[..., 0, 0] * Q[..., 1, 1] - Q[..., 0, 1] * Q[..., 1, 0]
    sign_q = np.sign(det_q)
    # A NaN never equals itself, so a non-finite child lands in the split branch.
    # An exact zero gives sign 0, which differs from +-1 and also splits.
    parity_ok = (sign_q == sign_q[:, :1]).all(axis=1)

    A = Q @ pinv0[compose[classes]]  # (n, 4, 2, 2), up to the common 2**(d+1)/h0
    s = sigma_min_2x2(A).min(axis=1) * (2.0 ** (level + 1)) / h0

    r = midpoint_deviation(beta_v, beta_m)
    keep = parity_ok & converged_from_deviation(r, s, min_img_sep)
    return keep, parity_ok, s


# ---------------------------------------------------------------------------
# Query kernels (backend-dispatched)
# ---------------------------------------------------------------------------


def triangle_weights(tri, beta) -> ArrayLike:
    """
    The three cross products that give containment and barycentric coordinates.

    With ``q1, q2, q3`` the triangle's mapped vertices, ``w_i`` is the cross
    product of the two edges of the sub-triangle opposite vertex ``i``. Then
    ``w1 + w2 + w3 == d`` identically, where ``d`` is twice the signed area, so
    ``w / d`` sums to one by construction and no matrix inverse is needed.

    Because a mesh vertex is stored once and referenced by index, two leaves
    sharing an edge form these products from bit-identical operands in opposite
    order. IEEE multiplication is commutative, so their weights on that edge are
    **exactly** negated and a query point can never fall through the seam between
    them.

    Parameters
    ----------
    tri: ArrayLike
        Source-plane triangle vertices, shape ``(T, 3, 2)``.

        *Unit: arcsec*

    beta: ArrayLike
        Query points, one per candidate, shape ``(T, 2)``.

        *Unit: arcsec*

    Returns
    -------
    ArrayLike
        Shape ``(T, 3)``.
    """
    q1 = tri[:, 0, :] - beta
    q2 = tri[:, 1, :] - beta
    q3 = tri[:, 2, :] - beta
    return backend.stack(
        (
            q2[:, 0] * q3[:, 1] - q2[:, 1] * q3[:, 0],
            q3[:, 0] * q1[:, 1] - q3[:, 1] * q1[:, 0],
            q1[:, 0] * q2[:, 1] - q1[:, 1] * q2[:, 0],
        ),
        dim=-1,
    )


def contains(w) -> ArrayLike:
    """
    Containment test: all three weights share a sign, zeros counting as inside.

    Source-plane images flip handedness across critical curves by design, so a
    fixed positive convention would be wrong on half the mesh. Since
    ``w1 + w2 + w3 == d``, "all three share a sign" implies that sign is
    ``sign(d)`` whenever ``d != 0`` -- so this is equivalent to testing against the
    triangle's own ``d``, while also being well defined when ``d`` is *exactly*
    zero. That case is reachable: three source-plane vertices can be exactly
    collinear in floating point, and a ``kappa = 1`` sheet maps every leaf to a
    point. Testing against ``sign(d) == 0`` would make every such leaf a hit for
    every query.

    Zeros counting as inside means a point on a shared edge returns both leaves.
    That is intended, and is the main reason candidate count is not image
    multiplicity.

    Parameters
    ----------
    w: ArrayLike
        Weights from :func:`triangle_weights`, shape ``(T, 3)``.

    Returns
    -------
    ArrayLike
        Shape ``(T,)`` bool.
    """
    nonneg = (w[..., 0] >= 0) & (w[..., 1] >= 0) & (w[..., 2] >= 0)
    nonpos = (w[..., 0] <= 0) & (w[..., 1] <= 0) & (w[..., 2] <= 0)
    return nonneg | nonpos


def sanitize_bary(w, d) -> ArrayLike:
    """
    Normalize weights to barycentric coordinates, clamping then falling back.

    ``d`` goes to zero on leaves straddling a critical curve, so ``w / d`` there is
    a ratio of two quantities at the roundoff floor -- unbounded, possibly outside
    the triangle, or ``NaN``. Two regimes, handled in order.

    The clip handles ordinary roundoff: a hit passed containment, so
    ``bary in [0, 1]**3`` holds mathematically and small excursions are numerical
    only. The centroid branch handles genuine breakdown, where ``w`` and ``d`` are
    both noise and the clipped components carry no information; it is also the only
    defined answer when they clip to all-zero. ``isfinite`` is checked *after* the
    clip, because clipping propagates ``NaN``.

    The centroid is a bounded fallback, not a guess. A leaf with ``d`` near zero
    reached the size floor, so its longest edge is at most ``min_img_sep`` and the
    centroid is within ``(2/3) * l_max`` of every point in it.

    Parameters
    ----------
    w: ArrayLike
        Weights of the hits, shape ``(K, 3)``.
    d: ArrayLike
        Twice the signed source-plane area of each hit leaf, shape ``(K,)``.

    Returns
    -------
    ArrayLike
        Shape ``(K, 3)``, guaranteed to lie in the simplex.
    """
    bary = backend.clamp(w / backend.unsqueeze(d, -1), 0.0, 1.0)
    total = bary[..., 0] + bary[..., 1] + bary[..., 2]
    ok = (
        (total > 0)
        & backend.isfinite(bary[..., 0])
        & backend.isfinite(bary[..., 1])
        & backend.isfinite(bary[..., 2])
    )
    safe = backend.where(ok, total, backend.ones_like(total))
    normed = bary / backend.unsqueeze(safe, -1)
    third = backend.ones_like(bary) / 3
    return backend.where(backend.unsqueeze(ok, -1), normed, third)
